### ISSUE TITLE
how about wechat？

### ISSUE THREAD

**Issue by cg200776** [easysoftware/redmine_social_sign_in#1]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN

**Comment by cg200776** [comment]
and QQ http://wiki.connect.qq.com/%E7%BD%91%E7%AB%99%E5%BA%94%E7%94%A8%E6%8E%A5%E5%85%A5%E6%B5%81%E7%A8%8B

**Comment by cg200776** [comment]
Expect to support their UnionID

**Comment by cg200776** [comment]
The registered users of these two platforms have exceeded 1 billion

**Comment by easy-petr** [comment]
Hello 

I will check it, thanks. 

Petr

**Comment by cg200776** [comment]
http://www.redmine.org/plugins/qqs

FYI

**Comment by cg200776** [comment]
Will you consider supporting it?

**Comment by easy-petr** [comment]
Yes, I will add it soon.

**Comment by easy-petr** [comment]
QQ connect added. Please check it I don't have their account. Thank you for your effort!

**Comment by cg200776** [comment]
I have encountered some problems and tried to send an e-mail to your company, but I can't contact you. Can you please leave me your e-mail address?  nuckychen@qq.com

**Comment by easy-petr** [comment]
Hi 

You write me to petr@easy.cz

Regards 
Petr

**Comment by easy-petr** [comment]
HI,

you can write me directly to petr@easy.cz.

If your Redmine is not accessble than is something wrong elsewhere. If you copy my plugin you have to run "bundle update" from commandline inside your Redmine app.

I will update Readme for install instructions.

Let me know if it helps

Regards,

Petr

**Comment by cg200776** [comment]
Thanks
QQconnect test passed
