### ISSUE TITLE
Error after redirect login

### ISSUE THREAD

**Issue by nam23690** [easysoftware/redmine_social_sign_in#3]
Hi, Please help me.
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.

I, [2018-09-13T16:11:27.702114 #2828]  INFO -- omniauth: (google_oauth2) Setup endpoint detected, running now.
I, [2018-09-13T16:11:27.703108 #2828]  INFO -- omniauth: (google_oauth2) Callback phase initiated.

**Comment by easy-petr** [comment]
Heloo try download a new version or send me more details - there is no info from log, thank you
