### ISSUE TITLE
I'm geting an Undefined local variable or method 'env' error Redmine  4.0.4.devel

### ISSUE THREAD

**Issue by dardbeqiri** [easysoftware/redmine_social_sign_in#4]
Current user: anonymous
Completed 500 Internal Server Error in 1187ms (ActiveRecord: 1.6ms)
  
NameError (undefined local variable or method `env' for #<RedmineSocialSignInCallbacksController:0x00005643b5a147e0>):
  
plugins/redmine_social_sign_in/app/controllers/redmine_social_sign_in_callbacks_controller.rb:6:in `social_sign_in_callback'

**Comment by dardbeqiri** [comment]
Further info:
Environment:
  Redmine version                4.0.4.devel
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_issue_dynamic_edit     0.6.7
  redmine_social_sign_in         1.0.2

**Comment by karma-ab** [comment]
Getting same error on callback. Providing static values to insert user method runs the login correctly. 

'env' variable is not accessible here. can anyone help?

**Comment by easy-petr** [comment]
Hello, I am going to fix it, thank you for your feedback

**Comment by karma-ab** [comment]
hi @easy-petr , thanks for replying, May I know the closing date of the issue?

Would really appreciate if it is done in few days as I will use it in my redmine instance for auth

**Comment by easy-petr** [comment]
I will release new verion on Thursday or Friday

**Comment by easy-petr** [comment]
Fixed, you can download a new code.
